# Generated by Django 5.0.1 on 2024-01-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Type_of_room',
            field=models.CharField(max_length=1),
        ),
    ]
