# Generated by Django 5.0.1 on 2024-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_room_number_of_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Number_of_room',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='Type_of_room',
            field=models.IntegerField(max_length=1),
        ),
    ]
